- name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: '20'

- name: Install Playwright
  run: |
    npm init -y
    npm install playwright@1.42.0
    npx playwright install --with-deps chromium

- name: Run snapshot script
  run: node scripts/snapshots.js
